languageCode: en
languageDirection: ltr
languageName: English
contentDir: content/en
hasCJKLanguage: false

title: Seven's Blog

params:
  sidebar:
    subtitle: The next time we may meet anywhere, but we are always as brilliant as a sea of stars.
  article:
    license:
      default: Licensed under CC BY-NC-SA 4.0
